server:
  port: 0

eureka:
  client:
    registryFetchIntervalSeconds: 5
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/

logging:
  pattern:
    level: '[trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}] %5p'

spring:
  zipkin: 
    baseUrl: http://192.168.99.100:9411/
  sleuth:
    sampler:
      percentage: 1.0