server:
  port: 8083

eureka:
  client:
    registryFetchIntervalSeconds: 5
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/

logging:
  pattern:
    level: '[trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}] %5p'

spring:
  zipkin: 
    baseUrl: http://192.168.99.100:9411/
  sleuth:
    sampler:
      percentage: 1.0

---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_PORT_8761_TCP_ADDR}:8761/eureka/
  instance:
    preferIpAddress: true