server:
  port: 0

eureka:
  client:
    registryFetchIntervalSeconds: 5
  serviceUrl:
    defaultZone: http://${EUREKA_PORT_8761_TCP_ADDR}:8761/eureka/

mongo:
  uri: mongodb://192.168.99.100:32773
  databaseName: raven

logging:
  pattern:
    level: '[trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}] %5p'

spring:
  zipkin: 
    baseUrl: http://192.168.99.100:9411/
  sleuth:
    sampler:
      percentage: 1.0
#  boot:
#    admin:
#      url: http://localhost:8090

management:
  health:
    mongo:
      enabled: false